# Generated by Django 4.0.2 on 2022-03-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrros',
            new_name='Carros',
        ),
    ]
