# Generated by Django 4.0.2 on 2022-03-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cadastro_delete_carros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
